version: "3.8"

services: 
  mongo:
    image: mongo:7
    container_name: reyu_mongo_prod
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_reyu_prod:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: always

  reyu_server:
    image: ${DOCKER_IMAGE}
    container_name: reyu_server_prod
    env_file:
      - ./src/.env
    ports: 
      - "7000:7000"
    volumes:
      - ./src/config/reyuDiamondKey.json:/app/dist/config/reyuDiamondKey.json
    depends_on:
      mongo:
        condition: service_healthy
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: reyu_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - reyu_server
    restart: always

  grafana:
    image: grafana/grafana
    container_name: reyu_grafana
    ports:
      - "5050:3000"
    volumes:
      - grafana_data_reyu:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always

volumes:
  mongo_data_reyu_prod:
  grafana_data_reyu:
